CREATE TABLE country
(
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL
);
CREATE UNIQUE INDEX id_UNIQUE ON country (id);
CREATE UNIQUE INDEX name_UNIQUE ON country (name);